
stages:
  - check
  - clean
  - build
# 构建 Job
check:
  stage: check
  tags:
    - maven
  script:
    - mvn -v
clean:
  stage: clean
  tags:
    - maven
  script:
    - mvn clean
build:
  stage: build
  tags:
    - maven
  script:
    - mvn install
    - ls ./target/*.jar
  artifacts:
    expire_in: 1 week
    paths:
      - ./target/*.jar